package com.jmy.dao;

import com.jmy.entity.Actionlog;
import com.jmy.entity.ActionlogExample;
import com.jmy.entity.ActionlogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActionlogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int countByExample(ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByExample(ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insert(ActionlogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insertSelective(ActionlogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<ActionlogWithBLOBs> selectByExampleWithBLOBs(ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Actionlog> selectByExample(ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	ActionlogWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ActionlogWithBLOBs record,
			@Param("example") ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") ActionlogWithBLOBs record,
			@Param("example") ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExample(@Param("record") Actionlog record, @Param("example") ActionlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeySelective(ActionlogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(ActionlogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_actionlog
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKey(Actionlog record);
}