package com.jmy.dao;

import com.jmy.entity.Faceinfo;
import com.jmy.entity.FaceinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FaceinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int countByExample(FaceinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByExample(FaceinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insert(Faceinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insertSelective(Faceinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Faceinfo> selectByExample(FaceinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	Faceinfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Faceinfo record, @Param("example") FaceinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExample(@Param("record") Faceinfo record, @Param("example") FaceinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Faceinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_faceinfo
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKey(Faceinfo record);
}