package com.jmy.dao;

import com.jmy.entity.Model;
import com.jmy.entity.ModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int countByExample(ModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByExample(ModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insert(Model record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insertSelective(Model record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Model> selectByExample(ModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	Model selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Model record, @Param("example") ModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExample(@Param("record") Model record, @Param("example") ModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Model record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKey(Model record);
}