package com.jmy.dao;

import com.jmy.entity.Modelext;
import com.jmy.entity.ModelextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModelextMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int countByExample(ModelextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByExample(ModelextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insert(Modelext record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insertSelective(Modelext record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Modelext> selectByExample(ModelextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	Modelext selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Modelext record, @Param("example") ModelextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExample(@Param("record") Modelext record, @Param("example") ModelextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Modelext record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelext
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKey(Modelext record);
}