package com.jmy.dao;

import com.jmy.entity.Modelapplay;
import com.jmy.entity.ModelapplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModelapplayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int countByExample(ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByExample(ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insert(Modelapplay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insertSelective(Modelapplay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Modelapplay> selectByExampleWithBLOBs(ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Modelapplay> selectByExample(ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	Modelapplay selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Modelapplay record, @Param("example") ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Modelapplay record, @Param("example") ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExample(@Param("record") Modelapplay record, @Param("example") ModelapplayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Modelapplay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Modelapplay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_modelapplay
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKey(Modelapplay record);
}