package com.jmy.dao;

import com.jmy.entity.Platuser;
import com.jmy.entity.PlatuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int countByExample(PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByExample(PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insert(Platuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int insertSelective(Platuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Platuser> selectByExampleWithBLOBs(PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	List<Platuser> selectByExample(PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	Platuser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Platuser record, @Param("example") PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Platuser record, @Param("example") PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByExample(@Param("record") Platuser record, @Param("example") PlatuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Platuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Platuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_platuser
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	int updateByPrimaryKey(Platuser record);
}