package com.jmy.dao;

import com.jmy.entity.SyInfos;
import com.jmy.entity.SyInfosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyInfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int countByExample(SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int deleteByExample(SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int insert(SyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int insertSelective(SyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    List<SyInfos> selectByExampleWithBLOBs(SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    List<SyInfos> selectByExample(SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    SyInfos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") SyInfos record, @Param("example") SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SyInfos record, @Param("example") SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int updateByExample(@Param("record") SyInfos record, @Param("example") SyInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int updateByPrimaryKeySelective(SyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SyInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syinfo
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    int updateByPrimaryKey(SyInfos record);
}