package com.jmy.dao;

import com.jmy.entity.Version;
import com.jmy.entity.VersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VersionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int countByExample(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int deleteByExample(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int insert(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int insertSelective(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	List<Version> selectByExampleWithBLOBs(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	List<Version> selectByExample(VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	Version selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Version record, @Param("example") VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Version record, @Param("example") VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int updateByExample(@Param("record") Version record, @Param("example") VersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int updateByPrimaryKeySelective(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Version record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table version
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	int updateByPrimaryKey(Version record);
}