package com.jmy.entity;

public class Action {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.cid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.action_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String actionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.sort
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte isdel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_action.remark
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.id
	 * @return  the value of isp_action.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.id
	 * @param id  the value for isp_action.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.cid
	 * @return  the value of isp_action.cid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.cid
	 * @param cid  the value for isp_action.cid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.name
	 * @return  the value of isp_action.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.name
	 * @param name  the value for isp_action.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.action_name
	 * @return  the value of isp_action.action_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getActionName() {
		return actionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.action_name
	 * @param actionName  the value for isp_action.action_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.sort
	 * @return  the value of isp_action.sort
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.sort
	 * @param sort  the value for isp_action.sort
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.create_time
	 * @return  the value of isp_action.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.create_time
	 * @param createTime  the value for isp_action.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.create_user
	 * @return  the value of isp_action.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.create_user
	 * @param createUser  the value for isp_action.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.update_time
	 * @return  the value of isp_action.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.update_time
	 * @param updateTime  the value for isp_action.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.update_user
	 * @return  the value of isp_action.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.update_user
	 * @param updateUser  the value for isp_action.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.isdel
	 * @return  the value of isp_action.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.isdel
	 * @param isdel  the value for isp_action.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setIsdel(Byte isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_action.remark
	 * @return  the value of isp_action.remark
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_action.remark
	 * @param remark  the value for isp_action.remark
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}