package com.jmy.entity;

public class Actionpackage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.sort
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_actionpackage.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte isdel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.id
	 * @return  the value of isp_actionpackage.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.id
	 * @param id  the value for isp_actionpackage.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.name
	 * @return  the value of isp_actionpackage.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.name
	 * @param name  the value for isp_actionpackage.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.money
	 * @return  the value of isp_actionpackage.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.money
	 * @param money  the value for isp_actionpackage.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setMoney(Integer money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.sort
	 * @return  the value of isp_actionpackage.sort
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.sort
	 * @param sort  the value for isp_actionpackage.sort
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.create_time
	 * @return  the value of isp_actionpackage.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.create_time
	 * @param createTime  the value for isp_actionpackage.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.create_user
	 * @return  the value of isp_actionpackage.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.create_user
	 * @param createUser  the value for isp_actionpackage.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.update_time
	 * @return  the value of isp_actionpackage.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.update_time
	 * @param updateTime  the value for isp_actionpackage.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.update_user
	 * @return  the value of isp_actionpackage.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.update_user
	 * @param updateUser  the value for isp_actionpackage.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_actionpackage.isdel
	 * @return  the value of isp_actionpackage.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_actionpackage.isdel
	 * @param isdel  the value for isp_actionpackage.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setIsdel(Byte isdel) {
		this.isdel = isdel;
	}
}