package com.jmy.entity;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_admin.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_admin.username
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_admin.password
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_admin.id
	 * @return  the value of isp_admin.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_admin.id
	 * @param id  the value for isp_admin.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_admin.username
	 * @return  the value of isp_admin.username
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_admin.username
	 * @param username  the value for isp_admin.username
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_admin.password
	 * @return  the value of isp_admin.password
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_admin.password
	 * @param password  the value for isp_admin.password
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}