package com.jmy.entity;

public class Area {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.pid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.level
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte isdel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_area.isarea
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte isarea;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.id
	 * @return  the value of isp_area.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.id
	 * @param id  the value for isp_area.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.code
	 * @return  the value of isp_area.code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.code
	 * @param code  the value for isp_area.code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.pid
	 * @return  the value of isp_area.pid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.pid
	 * @param pid  the value for isp_area.pid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.level
	 * @return  the value of isp_area.level
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.level
	 * @param level  the value for isp_area.level
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.status
	 * @return  the value of isp_area.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.status
	 * @param status  the value for isp_area.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.isdel
	 * @return  the value of isp_area.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.isdel
	 * @param isdel  the value for isp_area.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setIsdel(Byte isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_area.isarea
	 * @return  the value of isp_area.isarea
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getIsarea() {
		return isarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_area.isarea
	 * @param isarea  the value for isp_area.isarea
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setIsarea(Byte isarea) {
		this.isarea = isarea;
	}
}