package com.jmy.entity;

public class Faceext {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.fid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.addyear
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer addyear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.old_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer oldTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.new_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer newTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceext.message
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String message;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.id
	 * @return  the value of isp_faceext.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.id
	 * @param id  the value for isp_faceext.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.fid
	 * @return  the value of isp_faceext.fid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.fid
	 * @param fid  the value for isp_faceext.fid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setFid(Integer fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.addyear
	 * @return  the value of isp_faceext.addyear
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getAddyear() {
		return addyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.addyear
	 * @param addyear  the value for isp_faceext.addyear
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setAddyear(Integer addyear) {
		this.addyear = addyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.old_time
	 * @return  the value of isp_faceext.old_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getOldTime() {
		return oldTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.old_time
	 * @param oldTime  the value for isp_faceext.old_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setOldTime(Integer oldTime) {
		this.oldTime = oldTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.new_time
	 * @return  the value of isp_faceext.new_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getNewTime() {
		return newTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.new_time
	 * @param newTime  the value for isp_faceext.new_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setNewTime(Integer newTime) {
		this.newTime = newTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.money
	 * @return  the value of isp_faceext.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.money
	 * @param money  the value for isp_faceext.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setMoney(Integer money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.create_time
	 * @return  the value of isp_faceext.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.create_time
	 * @param createTime  the value for isp_faceext.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.create_user
	 * @return  the value of isp_faceext.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.create_user
	 * @param createUser  the value for isp_faceext.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceext.message
	 * @return  the value of isp_faceext.message
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceext.message
	 * @param message  the value for isp_faceext.message
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}