package com.jmy.entity;

public class Faceapplay {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.user_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.tao_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer taoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.years
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer years;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.check_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.check_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer checkUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_faceapplay.message
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String message;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.id
	 * @return  the value of isp_faceapplay.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.id
	 * @param id  the value for isp_faceapplay.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.user_id
	 * @return  the value of isp_faceapplay.user_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.user_id
	 * @param userId  the value for isp_faceapplay.user_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.tao_id
	 * @return  the value of isp_faceapplay.tao_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getTaoId() {
		return taoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.tao_id
	 * @param taoId  the value for isp_faceapplay.tao_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setTaoId(Integer taoId) {
		this.taoId = taoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.years
	 * @return  the value of isp_faceapplay.years
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getYears() {
		return years;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.years
	 * @param years  the value for isp_faceapplay.years
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setYears(Integer years) {
		this.years = years;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.money
	 * @return  the value of isp_faceapplay.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.money
	 * @param money  the value for isp_faceapplay.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setMoney(Integer money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.status
	 * @return  the value of isp_faceapplay.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.status
	 * @param status  the value for isp_faceapplay.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.create_time
	 * @return  the value of isp_faceapplay.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.create_time
	 * @param createTime  the value for isp_faceapplay.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.create_user
	 * @return  the value of isp_faceapplay.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.create_user
	 * @param createUser  the value for isp_faceapplay.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.update_time
	 * @return  the value of isp_faceapplay.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.update_time
	 * @param updateTime  the value for isp_faceapplay.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.update_user
	 * @return  the value of isp_faceapplay.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.update_user
	 * @param updateUser  the value for isp_faceapplay.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.check_time
	 * @return  the value of isp_faceapplay.check_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.check_time
	 * @param checkTime  the value for isp_faceapplay.check_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCheckTime(Integer checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.check_user
	 * @return  the value of isp_faceapplay.check_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCheckUser() {
		return checkUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.check_user
	 * @param checkUser  the value for isp_faceapplay.check_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCheckUser(Integer checkUser) {
		this.checkUser = checkUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_faceapplay.message
	 * @return  the value of isp_faceapplay.message
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_faceapplay.message
	 * @param message  the value for isp_faceapplay.message
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}