package com.jmy.entity;

import java.util.ArrayList;
import java.util.List;

public class GoodExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public GoodExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andModelIdIsNull() {
			addCriterion("model_id is null");
			return (Criteria) this;
		}

		public Criteria andModelIdIsNotNull() {
			addCriterion("model_id is not null");
			return (Criteria) this;
		}

		public Criteria andModelIdEqualTo(String value) {
			addCriterion("model_id =", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdNotEqualTo(String value) {
			addCriterion("model_id <>", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdGreaterThan(String value) {
			addCriterion("model_id >", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdGreaterThanOrEqualTo(String value) {
			addCriterion("model_id >=", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdLessThan(String value) {
			addCriterion("model_id <", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdLessThanOrEqualTo(String value) {
			addCriterion("model_id <=", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdLike(String value) {
			addCriterion("model_id like", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdNotLike(String value) {
			addCriterion("model_id not like", value, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdIn(List<String> values) {
			addCriterion("model_id in", values, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdNotIn(List<String> values) {
			addCriterion("model_id not in", values, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdBetween(String value1, String value2) {
			addCriterion("model_id between", value1, value2, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelIdNotBetween(String value1, String value2) {
			addCriterion("model_id not between", value1, value2, "modelId");
			return (Criteria) this;
		}

		public Criteria andModelCodeIsNull() {
			addCriterion("model_code is null");
			return (Criteria) this;
		}

		public Criteria andModelCodeIsNotNull() {
			addCriterion("model_code is not null");
			return (Criteria) this;
		}

		public Criteria andModelCodeEqualTo(String value) {
			addCriterion("model_code =", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeNotEqualTo(String value) {
			addCriterion("model_code <>", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeGreaterThan(String value) {
			addCriterion("model_code >", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeGreaterThanOrEqualTo(String value) {
			addCriterion("model_code >=", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeLessThan(String value) {
			addCriterion("model_code <", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeLessThanOrEqualTo(String value) {
			addCriterion("model_code <=", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeLike(String value) {
			addCriterion("model_code like", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeNotLike(String value) {
			addCriterion("model_code not like", value, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeIn(List<String> values) {
			addCriterion("model_code in", values, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeNotIn(List<String> values) {
			addCriterion("model_code not in", values, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeBetween(String value1, String value2) {
			addCriterion("model_code between", value1, value2, "modelCode");
			return (Criteria) this;
		}

		public Criteria andModelCodeNotBetween(String value1, String value2) {
			addCriterion("model_code not between", value1, value2, "modelCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeIsNull() {
			addCriterion("goods_code is null");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeIsNotNull() {
			addCriterion("goods_code is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeEqualTo(String value) {
			addCriterion("goods_code =", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeNotEqualTo(String value) {
			addCriterion("goods_code <>", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeGreaterThan(String value) {
			addCriterion("goods_code >", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeGreaterThanOrEqualTo(String value) {
			addCriterion("goods_code >=", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeLessThan(String value) {
			addCriterion("goods_code <", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeLessThanOrEqualTo(String value) {
			addCriterion("goods_code <=", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeLike(String value) {
			addCriterion("goods_code like", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeNotLike(String value) {
			addCriterion("goods_code not like", value, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeIn(List<String> values) {
			addCriterion("goods_code in", values, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeNotIn(List<String> values) {
			addCriterion("goods_code not in", values, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeBetween(String value1, String value2) {
			addCriterion("goods_code between", value1, value2, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andGoodsCodeNotBetween(String value1, String value2) {
			addCriterion("goods_code not between", value1, value2, "goodsCode");
			return (Criteria) this;
		}

		public Criteria andPicTimeIsNull() {
			addCriterion("pic_time is null");
			return (Criteria) this;
		}

		public Criteria andPicTimeIsNotNull() {
			addCriterion("pic_time is not null");
			return (Criteria) this;
		}

		public Criteria andPicTimeEqualTo(Integer value) {
			addCriterion("pic_time =", value, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeNotEqualTo(Integer value) {
			addCriterion("pic_time <>", value, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeGreaterThan(Integer value) {
			addCriterion("pic_time >", value, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("pic_time >=", value, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeLessThan(Integer value) {
			addCriterion("pic_time <", value, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeLessThanOrEqualTo(Integer value) {
			addCriterion("pic_time <=", value, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeIn(List<Integer> values) {
			addCriterion("pic_time in", values, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeNotIn(List<Integer> values) {
			addCriterion("pic_time not in", values, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeBetween(Integer value1, Integer value2) {
			addCriterion("pic_time between", value1, value2, "picTime");
			return (Criteria) this;
		}

		public Criteria andPicTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("pic_time not between", value1, value2, "picTime");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("app_id =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("app_id <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("app_id >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("app_id >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("app_id <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("app_id <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("app_id like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("app_id not like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("app_id in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("app_id not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAreaCodeIsNull() {
			addCriterion("area_code is null");
			return (Criteria) this;
		}

		public Criteria andAreaCodeIsNotNull() {
			addCriterion("area_code is not null");
			return (Criteria) this;
		}

		public Criteria andAreaCodeEqualTo(String value) {
			addCriterion("area_code =", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeNotEqualTo(String value) {
			addCriterion("area_code <>", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeGreaterThan(String value) {
			addCriterion("area_code >", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeGreaterThanOrEqualTo(String value) {
			addCriterion("area_code >=", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeLessThan(String value) {
			addCriterion("area_code <", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeLessThanOrEqualTo(String value) {
			addCriterion("area_code <=", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeLike(String value) {
			addCriterion("area_code like", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeNotLike(String value) {
			addCriterion("area_code not like", value, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeIn(List<String> values) {
			addCriterion("area_code in", values, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeNotIn(List<String> values) {
			addCriterion("area_code not in", values, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeBetween(String value1, String value2) {
			addCriterion("area_code between", value1, value2, "areaCode");
			return (Criteria) this;
		}

		public Criteria andAreaCodeNotBetween(String value1, String value2) {
			addCriterion("area_code not between", value1, value2, "areaCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeIsNull() {
			addCriterion("category_code is null");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeIsNotNull() {
			addCriterion("category_code is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeEqualTo(String value) {
			addCriterion("category_code =", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotEqualTo(String value) {
			addCriterion("category_code <>", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeGreaterThan(String value) {
			addCriterion("category_code >", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeGreaterThanOrEqualTo(String value) {
			addCriterion("category_code >=", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeLessThan(String value) {
			addCriterion("category_code <", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeLessThanOrEqualTo(String value) {
			addCriterion("category_code <=", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeLike(String value) {
			addCriterion("category_code like", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotLike(String value) {
			addCriterion("category_code not like", value, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeIn(List<String> values) {
			addCriterion("category_code in", values, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotIn(List<String> values) {
			addCriterion("category_code not in", values, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeBetween(String value1, String value2) {
			addCriterion("category_code between", value1, value2, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andCategoryCodeNotBetween(String value1, String value2) {
			addCriterion("category_code not between", value1, value2, "categoryCode");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andCheckNumIsNull() {
			addCriterion("check_num is null");
			return (Criteria) this;
		}

		public Criteria andCheckNumIsNotNull() {
			addCriterion("check_num is not null");
			return (Criteria) this;
		}

		public Criteria andCheckNumEqualTo(Integer value) {
			addCriterion("check_num =", value, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumNotEqualTo(Integer value) {
			addCriterion("check_num <>", value, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumGreaterThan(Integer value) {
			addCriterion("check_num >", value, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("check_num >=", value, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumLessThan(Integer value) {
			addCriterion("check_num <", value, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumLessThanOrEqualTo(Integer value) {
			addCriterion("check_num <=", value, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumIn(List<Integer> values) {
			addCriterion("check_num in", values, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumNotIn(List<Integer> values) {
			addCriterion("check_num not in", values, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumBetween(Integer value1, Integer value2) {
			addCriterion("check_num between", value1, value2, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCheckNumNotBetween(Integer value1, Integer value2) {
			addCriterion("check_num not between", value1, value2, "checkNum");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Integer value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Integer value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Integer value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Integer value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Integer> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Integer> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(Integer value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(Integer value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(Integer value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(Integer value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<Integer> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<Integer> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(Integer value1, Integer value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Integer value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Integer value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Integer value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Integer value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Integer> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Integer> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(Integer value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(Integer value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(Integer value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(Integer value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<Integer> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<Integer> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table isp_good
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table isp_good
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 20 20:47:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}