package com.jmy.entity;

public class Modelext {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.model_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String modelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte isdel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelext.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.id
	 * @return  the value of isp_modelext.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.id
	 * @param id  the value for isp_modelext.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.model_id
	 * @return  the value of isp_modelext.model_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getModelId() {
		return modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.model_id
	 * @param modelId  the value for isp_modelext.model_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setModelId(String modelId) {
		this.modelId = modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.name
	 * @return  the value of isp_modelext.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.name
	 * @param name  the value for isp_modelext.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.isdel
	 * @return  the value of isp_modelext.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.isdel
	 * @param isdel  the value for isp_modelext.isdel
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setIsdel(Byte isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.create_user
	 * @return  the value of isp_modelext.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.create_user
	 * @param createUser  the value for isp_modelext.create_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.create_time
	 * @return  the value of isp_modelext.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.create_time
	 * @param createTime  the value for isp_modelext.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.update_user
	 * @return  the value of isp_modelext.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.update_user
	 * @param updateUser  the value for isp_modelext.update_user
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelext.update_time
	 * @return  the value of isp_modelext.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelext.update_time
	 * @param updateTime  the value for isp_modelext.update_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}
}