package com.jmy.entity;

public class Modelapplay {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.type
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.old_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String oldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.auth_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String authCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.category_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.busy_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String busyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.app_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String appCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.front_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String frontCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.user_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.user_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_modelapplay.remarks
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.id
	 * @return  the value of isp_modelapplay.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.id
	 * @param id  the value for isp_modelapplay.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.name
	 * @return  the value of isp_modelapplay.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.name
	 * @param name  the value for isp_modelapplay.name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.type
	 * @return  the value of isp_modelapplay.type
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.type
	 * @param type  the value for isp_modelapplay.type
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.old_id
	 * @return  the value of isp_modelapplay.old_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getOldId() {
		return oldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.old_id
	 * @param oldId  the value for isp_modelapplay.old_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setOldId(String oldId) {
		this.oldId = oldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.auth_code
	 * @return  the value of isp_modelapplay.auth_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getAuthCode() {
		return authCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.auth_code
	 * @param authCode  the value for isp_modelapplay.auth_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.category_name
	 * @return  the value of isp_modelapplay.category_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.category_name
	 * @param categoryName  the value for isp_modelapplay.category_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.busy_code
	 * @return  the value of isp_modelapplay.busy_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getBusyCode() {
		return busyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.busy_code
	 * @param busyCode  the value for isp_modelapplay.busy_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setBusyCode(String busyCode) {
		this.busyCode = busyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.app_code
	 * @return  the value of isp_modelapplay.app_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getAppCode() {
		return appCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.app_code
	 * @param appCode  the value for isp_modelapplay.app_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.front_code
	 * @return  the value of isp_modelapplay.front_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getFrontCode() {
		return frontCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.front_code
	 * @param frontCode  the value for isp_modelapplay.front_code
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setFrontCode(String frontCode) {
		this.frontCode = frontCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.user_name
	 * @return  the value of isp_modelapplay.user_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.user_name
	 * @param userName  the value for isp_modelapplay.user_name
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.user_id
	 * @return  the value of isp_modelapplay.user_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.user_id
	 * @param userId  the value for isp_modelapplay.user_id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.status
	 * @return  the value of isp_modelapplay.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.status
	 * @param status  the value for isp_modelapplay.status
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.money
	 * @return  the value of isp_modelapplay.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.money
	 * @param money  the value for isp_modelapplay.money
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setMoney(Integer money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_modelapplay.remarks
	 * @return  the value of isp_modelapplay.remarks
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_modelapplay.remarks
	 * @param remarks  the value for isp_modelapplay.remarks
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}