package com.jmy.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public ModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andApplayIdIsNull() {
			addCriterion("applay_id is null");
			return (Criteria) this;
		}

		public Criteria andApplayIdIsNotNull() {
			addCriterion("applay_id is not null");
			return (Criteria) this;
		}

		public Criteria andApplayIdEqualTo(String value) {
			addCriterion("applay_id =", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdNotEqualTo(String value) {
			addCriterion("applay_id <>", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdGreaterThan(String value) {
			addCriterion("applay_id >", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdGreaterThanOrEqualTo(String value) {
			addCriterion("applay_id >=", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdLessThan(String value) {
			addCriterion("applay_id <", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdLessThanOrEqualTo(String value) {
			addCriterion("applay_id <=", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdLike(String value) {
			addCriterion("applay_id like", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdNotLike(String value) {
			addCriterion("applay_id not like", value, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdIn(List<String> values) {
			addCriterion("applay_id in", values, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdNotIn(List<String> values) {
			addCriterion("applay_id not in", values, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdBetween(String value1, String value2) {
			addCriterion("applay_id between", value1, value2, "applayId");
			return (Criteria) this;
		}

		public Criteria andApplayIdNotBetween(String value1, String value2) {
			addCriterion("applay_id not between", value1, value2, "applayId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAuthCodeIsNull() {
			addCriterion("auth_code is null");
			return (Criteria) this;
		}

		public Criteria andAuthCodeIsNotNull() {
			addCriterion("auth_code is not null");
			return (Criteria) this;
		}

		public Criteria andAuthCodeEqualTo(String value) {
			addCriterion("auth_code =", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeNotEqualTo(String value) {
			addCriterion("auth_code <>", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeGreaterThan(String value) {
			addCriterion("auth_code >", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeGreaterThanOrEqualTo(String value) {
			addCriterion("auth_code >=", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeLessThan(String value) {
			addCriterion("auth_code <", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeLessThanOrEqualTo(String value) {
			addCriterion("auth_code <=", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeLike(String value) {
			addCriterion("auth_code like", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeNotLike(String value) {
			addCriterion("auth_code not like", value, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeIn(List<String> values) {
			addCriterion("auth_code in", values, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeNotIn(List<String> values) {
			addCriterion("auth_code not in", values, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeBetween(String value1, String value2) {
			addCriterion("auth_code between", value1, value2, "authCode");
			return (Criteria) this;
		}

		public Criteria andAuthCodeNotBetween(String value1, String value2) {
			addCriterion("auth_code not between", value1, value2, "authCode");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIsNull() {
			addCriterion("category_name is null");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIsNotNull() {
			addCriterion("category_name is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryNameEqualTo(String value) {
			addCriterion("category_name =", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotEqualTo(String value) {
			addCriterion("category_name <>", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameGreaterThan(String value) {
			addCriterion("category_name >", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
			addCriterion("category_name >=", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLessThan(String value) {
			addCriterion("category_name <", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLessThanOrEqualTo(String value) {
			addCriterion("category_name <=", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLike(String value) {
			addCriterion("category_name like", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotLike(String value) {
			addCriterion("category_name not like", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIn(List<String> values) {
			addCriterion("category_name in", values, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotIn(List<String> values) {
			addCriterion("category_name not in", values, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameBetween(String value1, String value2) {
			addCriterion("category_name between", value1, value2, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotBetween(String value1, String value2) {
			addCriterion("category_name not between", value1, value2, "categoryName");
			return (Criteria) this;
		}

		public Criteria andFrontCodeIsNull() {
			addCriterion("front_code is null");
			return (Criteria) this;
		}

		public Criteria andFrontCodeIsNotNull() {
			addCriterion("front_code is not null");
			return (Criteria) this;
		}

		public Criteria andFrontCodeEqualTo(String value) {
			addCriterion("front_code =", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeNotEqualTo(String value) {
			addCriterion("front_code <>", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeGreaterThan(String value) {
			addCriterion("front_code >", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeGreaterThanOrEqualTo(String value) {
			addCriterion("front_code >=", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeLessThan(String value) {
			addCriterion("front_code <", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeLessThanOrEqualTo(String value) {
			addCriterion("front_code <=", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeLike(String value) {
			addCriterion("front_code like", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeNotLike(String value) {
			addCriterion("front_code not like", value, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeIn(List<String> values) {
			addCriterion("front_code in", values, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeNotIn(List<String> values) {
			addCriterion("front_code not in", values, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeBetween(String value1, String value2) {
			addCriterion("front_code between", value1, value2, "frontCode");
			return (Criteria) this;
		}

		public Criteria andFrontCodeNotBetween(String value1, String value2) {
			addCriterion("front_code not between", value1, value2, "frontCode");
			return (Criteria) this;
		}

		public Criteria andCurrentNumIsNull() {
			addCriterion("current_num is null");
			return (Criteria) this;
		}

		public Criteria andCurrentNumIsNotNull() {
			addCriterion("current_num is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentNumEqualTo(Long value) {
			addCriterion("current_num =", value, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumNotEqualTo(Long value) {
			addCriterion("current_num <>", value, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumGreaterThan(Long value) {
			addCriterion("current_num >", value, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumGreaterThanOrEqualTo(Long value) {
			addCriterion("current_num >=", value, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumLessThan(Long value) {
			addCriterion("current_num <", value, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumLessThanOrEqualTo(Long value) {
			addCriterion("current_num <=", value, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumIn(List<Long> values) {
			addCriterion("current_num in", values, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumNotIn(List<Long> values) {
			addCriterion("current_num not in", values, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumBetween(Long value1, Long value2) {
			addCriterion("current_num between", value1, value2, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentNumNotBetween(Long value1, Long value2) {
			addCriterion("current_num not between", value1, value2, "currentNum");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeIsNull() {
			addCriterion("current_code is null");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeIsNotNull() {
			addCriterion("current_code is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeEqualTo(String value) {
			addCriterion("current_code =", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeNotEqualTo(String value) {
			addCriterion("current_code <>", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeGreaterThan(String value) {
			addCriterion("current_code >", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeGreaterThanOrEqualTo(String value) {
			addCriterion("current_code >=", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeLessThan(String value) {
			addCriterion("current_code <", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeLessThanOrEqualTo(String value) {
			addCriterion("current_code <=", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeLike(String value) {
			addCriterion("current_code like", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeNotLike(String value) {
			addCriterion("current_code not like", value, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeIn(List<String> values) {
			addCriterion("current_code in", values, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeNotIn(List<String> values) {
			addCriterion("current_code not in", values, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeBetween(String value1, String value2) {
			addCriterion("current_code between", value1, value2, "currentCode");
			return (Criteria) this;
		}

		public Criteria andCurrentCodeNotBetween(String value1, String value2) {
			addCriterion("current_code not between", value1, value2, "currentCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeIsNull() {
			addCriterion("modeler_code is null");
			return (Criteria) this;
		}

		public Criteria andModelerCodeIsNotNull() {
			addCriterion("modeler_code is not null");
			return (Criteria) this;
		}

		public Criteria andModelerCodeEqualTo(String value) {
			addCriterion("modeler_code =", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeNotEqualTo(String value) {
			addCriterion("modeler_code <>", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeGreaterThan(String value) {
			addCriterion("modeler_code >", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeGreaterThanOrEqualTo(String value) {
			addCriterion("modeler_code >=", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeLessThan(String value) {
			addCriterion("modeler_code <", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeLessThanOrEqualTo(String value) {
			addCriterion("modeler_code <=", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeLike(String value) {
			addCriterion("modeler_code like", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeNotLike(String value) {
			addCriterion("modeler_code not like", value, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeIn(List<String> values) {
			addCriterion("modeler_code in", values, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeNotIn(List<String> values) {
			addCriterion("modeler_code not in", values, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeBetween(String value1, String value2) {
			addCriterion("modeler_code between", value1, value2, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andModelerCodeNotBetween(String value1, String value2) {
			addCriterion("modeler_code not between", value1, value2, "modelerCode");
			return (Criteria) this;
		}

		public Criteria andEffectNumIsNull() {
			addCriterion("effect_num is null");
			return (Criteria) this;
		}

		public Criteria andEffectNumIsNotNull() {
			addCriterion("effect_num is not null");
			return (Criteria) this;
		}

		public Criteria andEffectNumEqualTo(Long value) {
			addCriterion("effect_num =", value, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumNotEqualTo(Long value) {
			addCriterion("effect_num <>", value, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumGreaterThan(Long value) {
			addCriterion("effect_num >", value, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumGreaterThanOrEqualTo(Long value) {
			addCriterion("effect_num >=", value, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumLessThan(Long value) {
			addCriterion("effect_num <", value, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumLessThanOrEqualTo(Long value) {
			addCriterion("effect_num <=", value, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumIn(List<Long> values) {
			addCriterion("effect_num in", values, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumNotIn(List<Long> values) {
			addCriterion("effect_num not in", values, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumBetween(Long value1, Long value2) {
			addCriterion("effect_num between", value1, value2, "effectNum");
			return (Criteria) this;
		}

		public Criteria andEffectNumNotBetween(Long value1, Long value2) {
			addCriterion("effect_num not between", value1, value2, "effectNum");
			return (Criteria) this;
		}

		public Criteria andSystemIdIsNull() {
			addCriterion("system_id is null");
			return (Criteria) this;
		}

		public Criteria andSystemIdIsNotNull() {
			addCriterion("system_id is not null");
			return (Criteria) this;
		}

		public Criteria andSystemIdEqualTo(String value) {
			addCriterion("system_id =", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdNotEqualTo(String value) {
			addCriterion("system_id <>", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdGreaterThan(String value) {
			addCriterion("system_id >", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdGreaterThanOrEqualTo(String value) {
			addCriterion("system_id >=", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdLessThan(String value) {
			addCriterion("system_id <", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdLessThanOrEqualTo(String value) {
			addCriterion("system_id <=", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdLike(String value) {
			addCriterion("system_id like", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdNotLike(String value) {
			addCriterion("system_id not like", value, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdIn(List<String> values) {
			addCriterion("system_id in", values, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdNotIn(List<String> values) {
			addCriterion("system_id not in", values, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdBetween(String value1, String value2) {
			addCriterion("system_id between", value1, value2, "systemId");
			return (Criteria) this;
		}

		public Criteria andSystemIdNotBetween(String value1, String value2) {
			addCriterion("system_id not between", value1, value2, "systemId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andValidatyIsNull() {
			addCriterion("validaty is null");
			return (Criteria) this;
		}

		public Criteria andValidatyIsNotNull() {
			addCriterion("validaty is not null");
			return (Criteria) this;
		}

		public Criteria andValidatyEqualTo(Date value) {
			addCriterion("validaty =", value, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyNotEqualTo(Date value) {
			addCriterion("validaty <>", value, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyGreaterThan(Date value) {
			addCriterion("validaty >", value, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyGreaterThanOrEqualTo(Date value) {
			addCriterion("validaty >=", value, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyLessThan(Date value) {
			addCriterion("validaty <", value, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyLessThanOrEqualTo(Date value) {
			addCriterion("validaty <=", value, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyIn(List<Date> values) {
			addCriterion("validaty in", values, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyNotIn(List<Date> values) {
			addCriterion("validaty not in", values, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyBetween(Date value1, Date value2) {
			addCriterion("validaty between", value1, value2, "validaty");
			return (Criteria) this;
		}

		public Criteria andValidatyNotBetween(Date value1, Date value2) {
			addCriterion("validaty not between", value1, value2, "validaty");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Integer value) {
			addCriterion("money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Integer value) {
			addCriterion("money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Integer value) {
			addCriterion("money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Integer value) {
			addCriterion("money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Integer value) {
			addCriterion("money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Integer value) {
			addCriterion("money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Integer> values) {
			addCriterion("money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Integer> values) {
			addCriterion("money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Integer value1, Integer value2) {
			addCriterion("money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Integer value1, Integer value2) {
			addCriterion("money not between", value1, value2, "money");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table isp_model
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table isp_model
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 20 20:47:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}