package com.jmy.entity;

public class Noticeread {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_noticeread.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_noticeread.uid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_noticeread.nid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer nid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column isp_noticeread.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	private Integer createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_noticeread.id
	 * @return  the value of isp_noticeread.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_noticeread.id
	 * @param id  the value for isp_noticeread.id
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_noticeread.uid
	 * @return  the value of isp_noticeread.uid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_noticeread.uid
	 * @param uid  the value for isp_noticeread.uid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_noticeread.nid
	 * @return  the value of isp_noticeread.nid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getNid() {
		return nid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_noticeread.nid
	 * @param nid  the value for isp_noticeread.nid
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setNid(Integer nid) {
		this.nid = nid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column isp_noticeread.create_time
	 * @return  the value of isp_noticeread.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column isp_noticeread.create_time
	 * @param createTime  the value for isp_noticeread.create_time
	 * @mbggenerated  Mon Mar 27 19:10:41 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}
}