package com.jmy.dao;

import com.jmy.entity.Enterprise;
import com.jmy.entity.EnterpriseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnterpriseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int countByExample(EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByExample(EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insert(Enterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insertSelective(Enterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	List<Enterprise> selectByExample(EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	Enterprise selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Enterprise record, @Param("example") EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExample(@Param("record") Enterprise record, @Param("example") EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKeySelective(Enterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKey(Enterprise record);
}