package com.jmy.dao;

import com.jmy.entity.NoticeRead;
import com.jmy.entity.NoticeReadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeReadMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int countByExample(NoticeReadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByExample(NoticeReadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insert(NoticeRead record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insertSelective(NoticeRead record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	List<NoticeRead> selectByExample(NoticeReadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	NoticeRead selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NoticeRead record, @Param("example") NoticeReadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExample(@Param("record") NoticeRead record, @Param("example") NoticeReadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKeySelective(NoticeRead record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table noticeread
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKey(NoticeRead record);
}