package com.jmy.dao;

import com.jmy.entity.PhoneSend;
import com.jmy.entity.PhoneSendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneSendMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int countByExample(PhoneSendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByExample(PhoneSendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insert(PhoneSend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insertSelective(PhoneSend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	List<PhoneSend> selectByExample(PhoneSendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	PhoneSend selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PhoneSend record, @Param("example") PhoneSendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExample(@Param("record") PhoneSend record, @Param("example") PhoneSendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKeySelective(PhoneSend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phone_send
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKey(PhoneSend record);
}