package com.jmy.dao;

import com.jmy.entity.Swjg;
import com.jmy.entity.SwjgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SwjgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int countByExample(SwjgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByExample(SwjgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByPrimaryKey(String swjgDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insert(Swjg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insertSelective(Swjg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	List<Swjg> selectByExample(SwjgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	Swjg selectByPrimaryKey(String swjgDm);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Swjg record, @Param("example") SwjgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExample(@Param("record") Swjg record, @Param("example") SwjgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKeySelective(Swjg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swjg
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKey(Swjg record);
}