package com.jmy.dao;

import com.jmy.entity.TimeNotice;
import com.jmy.entity.TimeNoticeExample;
import com.jmy.entity.TimeNoticeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeNoticeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int countByExample(TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByExample(TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insert(TimeNoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int insertSelective(TimeNoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	List<TimeNoticeWithBLOBs> selectByExampleWithBLOBs(TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	List<TimeNotice> selectByExample(TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	TimeNoticeWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TimeNoticeWithBLOBs record,
			@Param("example") TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") TimeNoticeWithBLOBs record,
			@Param("example") TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByExample(@Param("record") TimeNotice record, @Param("example") TimeNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKeySelective(TimeNoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(TimeNoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_notice
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	int updateByPrimaryKey(TimeNotice record);
}