package com.jmy.entity;

public class App {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.path
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.version
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app.name
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.id
	 * @return  the value of app.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.id
	 * @param id  the value for app.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.path
	 * @return  the value of app.path
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.path
	 * @param path  the value for app.path
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.version
	 * @return  the value of app.version
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.version
	 * @param version  the value for app.version
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app.name
	 * @return  the value of app.name
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app.name
	 * @param name  the value for app.name
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}