package com.jmy.entity;

public class AppRead {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_read.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_read.enterprise_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_read.app_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_read.is_read
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Byte isRead;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_read.read_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long readTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_read.id
	 * @return  the value of app_read.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_read.id
	 * @param id  the value for app_read.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_read.enterprise_id
	 * @return  the value of app_read.enterprise_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_read.enterprise_id
	 * @param enterpriseId  the value for app_read.enterprise_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_read.app_id
	 * @return  the value of app_read.app_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_read.app_id
	 * @param appId  the value for app_read.app_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_read.is_read
	 * @return  the value of app_read.is_read
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Byte getIsRead() {
		return isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_read.is_read
	 * @param isRead  the value for app_read.is_read
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setIsRead(Byte isRead) {
		this.isRead = isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_read.read_time
	 * @return  the value of app_read.read_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getReadTime() {
		return readTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_read.read_time
	 * @param readTime  the value for app_read.read_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setReadTime(Long readTime) {
		this.readTime = readTime;
	}
}