package com.jmy.entity;

public class NoticeWithBLOBs extends Notice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.content
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.message
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String message;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.content
	 * @return  the value of notice.content
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.content
	 * @param content  the value for notice.content
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.message
	 * @return  the value of notice.message
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.message
	 * @param message  the value for notice.message
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}