package com.jmy.entity;

public class Notice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.title
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.create_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer createUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.id
	 * @return  the value of notice.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.id
	 * @param id  the value for notice.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.title
	 * @return  the value of notice.title
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.title
	 * @param title  the value for notice.title
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.create_time
	 * @return  the value of notice.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.create_time
	 * @param createTime  the value for notice.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.create_user
	 * @return  the value of notice.create_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.create_user
	 * @param createUser  the value for notice.create_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}
}