package com.jmy.entity;

public class NoticeRead {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column noticeread.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column noticeread.uid
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column noticeread.nid
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer nid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column noticeread.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column noticeread.id
	 * @return  the value of noticeread.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column noticeread.id
	 * @param id  the value for noticeread.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column noticeread.uid
	 * @return  the value of noticeread.uid
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column noticeread.uid
	 * @param uid  the value for noticeread.uid
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column noticeread.nid
	 * @return  the value of noticeread.nid
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getNid() {
		return nid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column noticeread.nid
	 * @param nid  the value for noticeread.nid
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setNid(Integer nid) {
		this.nid = nid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column noticeread.create_time
	 * @return  the value of noticeread.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column noticeread.create_time
	 * @param createTime  the value for noticeread.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}
}