package com.jmy.entity;

public class PhoneSend {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phone_send.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phone_send.enterprise_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phone_send.phone_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer phoneId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phone_send.id
	 * @return  the value of phone_send.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phone_send.id
	 * @param id  the value for phone_send.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phone_send.enterprise_id
	 * @return  the value of phone_send.enterprise_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phone_send.enterprise_id
	 * @param enterpriseId  the value for phone_send.enterprise_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phone_send.phone_id
	 * @return  the value of phone_send.phone_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getPhoneId() {
		return phoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phone_send.phone_id
	 * @param phoneId  the value for phone_send.phone_id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setPhoneId(Integer phoneId) {
		this.phoneId = phoneId;
	}
}