package com.jmy.entity;

public class PreTime {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pre_time.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pre_time.last_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long lastTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pre_time.now_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long nowTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pre_time.is_use
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Byte isUse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pre_time.id
	 * @return  the value of pre_time.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pre_time.id
	 * @param id  the value for pre_time.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pre_time.last_time
	 * @return  the value of pre_time.last_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getLastTime() {
		return lastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pre_time.last_time
	 * @param lastTime  the value for pre_time.last_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setLastTime(Long lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pre_time.now_time
	 * @return  the value of pre_time.now_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getNowTime() {
		return nowTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pre_time.now_time
	 * @param nowTime  the value for pre_time.now_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setNowTime(Long nowTime) {
		this.nowTime = nowTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pre_time.is_use
	 * @return  the value of pre_time.is_use
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Byte getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pre_time.is_use
	 * @param isUse  the value for pre_time.is_use
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setIsUse(Byte isUse) {
		this.isUse = isUse;
	}
}