package com.jmy.entity;

public class Swjg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swjg.SWJG_DM
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String swjgDm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swjg.SWJGMC
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String swjgmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swjg.SWJGJC
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String swjgjc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swjg.SWJGBZ
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String swjgbz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swjg.SJSWJG_DM
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String sjswjgDm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swjg.SWJG_DM
	 * @return  the value of swjg.SWJG_DM
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getSwjgDm() {
		return swjgDm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swjg.SWJG_DM
	 * @param swjgDm  the value for swjg.SWJG_DM
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setSwjgDm(String swjgDm) {
		this.swjgDm = swjgDm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swjg.SWJGMC
	 * @return  the value of swjg.SWJGMC
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getSwjgmc() {
		return swjgmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swjg.SWJGMC
	 * @param swjgmc  the value for swjg.SWJGMC
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setSwjgmc(String swjgmc) {
		this.swjgmc = swjgmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swjg.SWJGJC
	 * @return  the value of swjg.SWJGJC
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getSwjgjc() {
		return swjgjc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swjg.SWJGJC
	 * @param swjgjc  the value for swjg.SWJGJC
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setSwjgjc(String swjgjc) {
		this.swjgjc = swjgjc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swjg.SWJGBZ
	 * @return  the value of swjg.SWJGBZ
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getSwjgbz() {
		return swjgbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swjg.SWJGBZ
	 * @param swjgbz  the value for swjg.SWJGBZ
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setSwjgbz(String swjgbz) {
		this.swjgbz = swjgbz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swjg.SJSWJG_DM
	 * @return  the value of swjg.SJSWJG_DM
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getSjswjgDm() {
		return sjswjgDm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swjg.SJSWJG_DM
	 * @param sjswjgDm  the value for swjg.SJSWJG_DM
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setSjswjgDm(String sjswjgDm) {
		this.sjswjgDm = sjswjgDm;
	}
}