package com.jmy.entity;

public class TimeNotice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.title
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.is_del
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Byte isDel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.is_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Byte isTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.send_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private String sendTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.create_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.update_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Integer updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_notice.update_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	private Long updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.id
	 * @return  the value of time_notice.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.id
	 * @param id  the value for time_notice.id
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.title
	 * @return  the value of time_notice.title
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.title
	 * @param title  the value for time_notice.title
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.is_del
	 * @return  the value of time_notice.is_del
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Byte getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.is_del
	 * @param isDel  the value for time_notice.is_del
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setIsDel(Byte isDel) {
		this.isDel = isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.is_time
	 * @return  the value of time_notice.is_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Byte getIsTime() {
		return isTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.is_time
	 * @param isTime  the value for time_notice.is_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setIsTime(Byte isTime) {
		this.isTime = isTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.send_time
	 * @return  the value of time_notice.send_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public String getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.send_time
	 * @param sendTime  the value for time_notice.send_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setSendTime(String sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.create_user
	 * @return  the value of time_notice.create_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.create_user
	 * @param createUser  the value for time_notice.create_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.create_time
	 * @return  the value of time_notice.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.create_time
	 * @param createTime  the value for time_notice.create_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.update_user
	 * @return  the value of time_notice.update_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.update_user
	 * @param updateUser  the value for time_notice.update_user
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_notice.update_time
	 * @return  the value of time_notice.update_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_notice.update_time
	 * @param updateTime  the value for time_notice.update_time
	 * @mbggenerated  Thu Jun 15 15:30:48 CST 2017
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}
}