package com.jmy.entity;

public class SyInfos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.name
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.is_href
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Byte isHref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.sort
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.version_id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.is_del
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Byte isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syinfo.content
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.id
     *
     * @return the value of syinfo.id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.id
     *
     * @param id the value for syinfo.id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.name
     *
     * @return the value of syinfo.name
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.name
     *
     * @param name the value for syinfo.name
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.is_href
     *
     * @return the value of syinfo.is_href
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Byte getIsHref() {
        return isHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.is_href
     *
     * @param isHref the value for syinfo.is_href
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setIsHref(Byte isHref) {
        this.isHref = isHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.sort
     *
     * @return the value of syinfo.sort
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.sort
     *
     * @param sort the value for syinfo.sort
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.version_id
     *
     * @return the value of syinfo.version_id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.version_id
     *
     * @param versionId the value for syinfo.version_id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.is_del
     *
     * @return the value of syinfo.is_del
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.is_del
     *
     * @param isDel the value for syinfo.is_del
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syinfo.content
     *
     * @return the value of syinfo.content
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syinfo.content
     *
     * @param content the value for syinfo.content
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}