package com.jmy.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.secret
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private String secret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isdel
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Byte isdel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.createtime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.createuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.updatetime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.updateuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer updateuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.checktime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer checktime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.checkuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	private Integer checkuser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.secret
	 * @return  the value of user.secret
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public String getSecret() {
		return secret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.secret
	 * @param secret  the value for user.secret
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setSecret(String secret) {
		this.secret = secret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isdel
	 * @return  the value of user.isdel
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Byte getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isdel
	 * @param isdel  the value for user.isdel
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setIsdel(Byte isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.createtime
	 * @return  the value of user.createtime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.createtime
	 * @param createtime  the value for user.createtime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setCreatetime(Integer createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.createuser
	 * @return  the value of user.createuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.createuser
	 * @param createuser  the value for user.createuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setCreateuser(Integer createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.updatetime
	 * @return  the value of user.updatetime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.updatetime
	 * @param updatetime  the value for user.updatetime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setUpdatetime(Integer updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.updateuser
	 * @return  the value of user.updateuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getUpdateuser() {
		return updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.updateuser
	 * @param updateuser  the value for user.updateuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setUpdateuser(Integer updateuser) {
		this.updateuser = updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.checktime
	 * @return  the value of user.checktime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.checktime
	 * @param checktime  the value for user.checktime
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setChecktime(Integer checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.checkuser
	 * @return  the value of user.checkuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Integer getCheckuser() {
		return checkuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.checkuser
	 * @param checkuser  the value for user.checkuser
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setCheckuser(Integer checkuser) {
		this.checkuser = checkuser;
	}
}