package com.jmy.entity;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andSecretIsNull() {
			addCriterion("secret is null");
			return (Criteria) this;
		}

		public Criteria andSecretIsNotNull() {
			addCriterion("secret is not null");
			return (Criteria) this;
		}

		public Criteria andSecretEqualTo(String value) {
			addCriterion("secret =", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotEqualTo(String value) {
			addCriterion("secret <>", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretGreaterThan(String value) {
			addCriterion("secret >", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretGreaterThanOrEqualTo(String value) {
			addCriterion("secret >=", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLessThan(String value) {
			addCriterion("secret <", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLessThanOrEqualTo(String value) {
			addCriterion("secret <=", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLike(String value) {
			addCriterion("secret like", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotLike(String value) {
			addCriterion("secret not like", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretIn(List<String> values) {
			addCriterion("secret in", values, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotIn(List<String> values) {
			addCriterion("secret not in", values, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretBetween(String value1, String value2) {
			addCriterion("secret between", value1, value2, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotBetween(String value1, String value2) {
			addCriterion("secret not between", value1, value2, "secret");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andIsdelIsNull() {
			addCriterion("isdel is null");
			return (Criteria) this;
		}

		public Criteria andIsdelIsNotNull() {
			addCriterion("isdel is not null");
			return (Criteria) this;
		}

		public Criteria andIsdelEqualTo(Byte value) {
			addCriterion("isdel =", value, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelNotEqualTo(Byte value) {
			addCriterion("isdel <>", value, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelGreaterThan(Byte value) {
			addCriterion("isdel >", value, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelGreaterThanOrEqualTo(Byte value) {
			addCriterion("isdel >=", value, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelLessThan(Byte value) {
			addCriterion("isdel <", value, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelLessThanOrEqualTo(Byte value) {
			addCriterion("isdel <=", value, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelIn(List<Byte> values) {
			addCriterion("isdel in", values, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelNotIn(List<Byte> values) {
			addCriterion("isdel not in", values, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelBetween(Byte value1, Byte value2) {
			addCriterion("isdel between", value1, value2, "isdel");
			return (Criteria) this;
		}

		public Criteria andIsdelNotBetween(Byte value1, Byte value2) {
			addCriterion("isdel not between", value1, value2, "isdel");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createtime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createtime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Integer value) {
			addCriterion("createtime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Integer value) {
			addCriterion("createtime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Integer value) {
			addCriterion("createtime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("createtime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Integer value) {
			addCriterion("createtime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Integer value) {
			addCriterion("createtime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Integer> values) {
			addCriterion("createtime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Integer> values) {
			addCriterion("createtime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Integer value1, Integer value2) {
			addCriterion("createtime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Integer value1, Integer value2) {
			addCriterion("createtime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreateuserIsNull() {
			addCriterion("createuser is null");
			return (Criteria) this;
		}

		public Criteria andCreateuserIsNotNull() {
			addCriterion("createuser is not null");
			return (Criteria) this;
		}

		public Criteria andCreateuserEqualTo(Integer value) {
			addCriterion("createuser =", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotEqualTo(Integer value) {
			addCriterion("createuser <>", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserGreaterThan(Integer value) {
			addCriterion("createuser >", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserGreaterThanOrEqualTo(Integer value) {
			addCriterion("createuser >=", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserLessThan(Integer value) {
			addCriterion("createuser <", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserLessThanOrEqualTo(Integer value) {
			addCriterion("createuser <=", value, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserIn(List<Integer> values) {
			addCriterion("createuser in", values, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotIn(List<Integer> values) {
			addCriterion("createuser not in", values, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserBetween(Integer value1, Integer value2) {
			addCriterion("createuser between", value1, value2, "createuser");
			return (Criteria) this;
		}

		public Criteria andCreateuserNotBetween(Integer value1, Integer value2) {
			addCriterion("createuser not between", value1, value2, "createuser");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updatetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Integer value) {
			addCriterion("updatetime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Integer value) {
			addCriterion("updatetime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Integer value) {
			addCriterion("updatetime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("updatetime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Integer value) {
			addCriterion("updatetime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Integer value) {
			addCriterion("updatetime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Integer> values) {
			addCriterion("updatetime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Integer> values) {
			addCriterion("updatetime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Integer value1, Integer value2) {
			addCriterion("updatetime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Integer value1, Integer value2) {
			addCriterion("updatetime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateuserIsNull() {
			addCriterion("updateuser is null");
			return (Criteria) this;
		}

		public Criteria andUpdateuserIsNotNull() {
			addCriterion("updateuser is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateuserEqualTo(Integer value) {
			addCriterion("updateuser =", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotEqualTo(Integer value) {
			addCriterion("updateuser <>", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserGreaterThan(Integer value) {
			addCriterion("updateuser >", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserGreaterThanOrEqualTo(Integer value) {
			addCriterion("updateuser >=", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserLessThan(Integer value) {
			addCriterion("updateuser <", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserLessThanOrEqualTo(Integer value) {
			addCriterion("updateuser <=", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserIn(List<Integer> values) {
			addCriterion("updateuser in", values, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotIn(List<Integer> values) {
			addCriterion("updateuser not in", values, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserBetween(Integer value1, Integer value2) {
			addCriterion("updateuser between", value1, value2, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotBetween(Integer value1, Integer value2) {
			addCriterion("updateuser not between", value1, value2, "updateuser");
			return (Criteria) this;
		}

		public Criteria andChecktimeIsNull() {
			addCriterion("checktime is null");
			return (Criteria) this;
		}

		public Criteria andChecktimeIsNotNull() {
			addCriterion("checktime is not null");
			return (Criteria) this;
		}

		public Criteria andChecktimeEqualTo(Integer value) {
			addCriterion("checktime =", value, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeNotEqualTo(Integer value) {
			addCriterion("checktime <>", value, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeGreaterThan(Integer value) {
			addCriterion("checktime >", value, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("checktime >=", value, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeLessThan(Integer value) {
			addCriterion("checktime <", value, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeLessThanOrEqualTo(Integer value) {
			addCriterion("checktime <=", value, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeIn(List<Integer> values) {
			addCriterion("checktime in", values, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeNotIn(List<Integer> values) {
			addCriterion("checktime not in", values, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeBetween(Integer value1, Integer value2) {
			addCriterion("checktime between", value1, value2, "checktime");
			return (Criteria) this;
		}

		public Criteria andChecktimeNotBetween(Integer value1, Integer value2) {
			addCriterion("checktime not between", value1, value2, "checktime");
			return (Criteria) this;
		}

		public Criteria andCheckuserIsNull() {
			addCriterion("checkuser is null");
			return (Criteria) this;
		}

		public Criteria andCheckuserIsNotNull() {
			addCriterion("checkuser is not null");
			return (Criteria) this;
		}

		public Criteria andCheckuserEqualTo(Integer value) {
			addCriterion("checkuser =", value, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserNotEqualTo(Integer value) {
			addCriterion("checkuser <>", value, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserGreaterThan(Integer value) {
			addCriterion("checkuser >", value, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserGreaterThanOrEqualTo(Integer value) {
			addCriterion("checkuser >=", value, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserLessThan(Integer value) {
			addCriterion("checkuser <", value, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserLessThanOrEqualTo(Integer value) {
			addCriterion("checkuser <=", value, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserIn(List<Integer> values) {
			addCriterion("checkuser in", values, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserNotIn(List<Integer> values) {
			addCriterion("checkuser not in", values, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserBetween(Integer value1, Integer value2) {
			addCriterion("checkuser between", value1, value2, "checkuser");
			return (Criteria) this;
		}

		public Criteria andCheckuserNotBetween(Integer value1, Integer value2) {
			addCriterion("checkuser not between", value1, value2, "checkuser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Sat Jun 17 10:59:42 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 14 17:47:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}