package com.jmy.entity;

public class VersionExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.vid
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.addyear
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer addyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.old_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer oldTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.new_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer newTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.money
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.create_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.create_user
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_ext.message
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.id
     *
     * @return the value of version_ext.id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.id
     *
     * @param id the value for version_ext.id
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.vid
     *
     * @return the value of version_ext.vid
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.vid
     *
     * @param vid the value for version_ext.vid
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.addyear
     *
     * @return the value of version_ext.addyear
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getAddyear() {
        return addyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.addyear
     *
     * @param addyear the value for version_ext.addyear
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setAddyear(Integer addyear) {
        this.addyear = addyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.old_time
     *
     * @return the value of version_ext.old_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getOldTime() {
        return oldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.old_time
     *
     * @param oldTime the value for version_ext.old_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setOldTime(Integer oldTime) {
        this.oldTime = oldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.new_time
     *
     * @return the value of version_ext.new_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getNewTime() {
        return newTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.new_time
     *
     * @param newTime the value for version_ext.new_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setNewTime(Integer newTime) {
        this.newTime = newTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.money
     *
     * @return the value of version_ext.money
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.money
     *
     * @param money the value for version_ext.money
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.create_time
     *
     * @return the value of version_ext.create_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.create_time
     *
     * @param createTime the value for version_ext.create_time
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.create_user
     *
     * @return the value of version_ext.create_user
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.create_user
     *
     * @param createUser the value for version_ext.create_user
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_ext.message
     *
     * @return the value of version_ext.message
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_ext.message
     *
     * @param message the value for version_ext.message
     *
     * @mbggenerated Sat Jun 17 10:59:42 CST 2017
     */
    public void setMessage(String message) {
        this.message = message;
    }
}